In [1]:
import numpy as np

# Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr = np.array([1, 2.5, '3'])
arr

array(['1', '2.5', '3'], dtype='<U32')

In [5]:
arr = np.array([1, 2.3])
arr

array([1. , 2.3])

In [6]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [7]:
arr = np.array([1, 2, 3, 4, 5], dtype=float, ndmin=5)
arr

array([[[[[1., 2., 3., 4., 5.]]]]])

In [8]:
arr.ndim

5

# AsArray

In [9]:
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.asarray(l)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
t = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
arr = np.asarray(t)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr.dtype

dtype('int32')

In [13]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
arr = np.arange(0, 1000, 10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [15]:
arr.shape

(100,)

In [16]:
arr.reshape(10, 10)

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

In [17]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

In [18]:
arr.reshape(50, 2)

array([[  0,  10],
       [ 20,  30],
       [ 40,  50],
       [ 60,  70],
       [ 80,  90],
       [100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190],
       [200, 210],
       [220, 230],
       [240, 250],
       [260, 270],
       [280, 290],
       [300, 310],
       [320, 330],
       [340, 350],
       [360, 370],
       [380, 390],
       [400, 410],
       [420, 430],
       [440, 450],
       [460, 470],
       [480, 490],
       [500, 510],
       [520, 530],
       [540, 550],
       [560, 570],
       [580, 590],
       [600, 610],
       [620, 630],
       [640, 650],
       [660, 670],
       [680, 690],
       [700, 710],
       [720, 730],
       [740, 750],
       [760, 770],
       [780, 790],
       [800, 810],
       [820, 830],
       [840, 850],
       [860, 870],
       [880, 890],
       [900, 910],
       [920, 930],
       [940, 950],
       [960, 970],
       [980, 990]])

In [19]:
arr.reshape(20, 5)

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540],
       [550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640],
       [650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740],
       [750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840],
       [850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940],
       [950, 960, 970, 980, 990]])

In [20]:
arr.resize(10, 10)

In [21]:
arr

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

# From Function

In [22]:
def function_1(i, j):
    return i*j

In [24]:
function_1(2, 3)

6

In [25]:
func = function_1

In [26]:
np.fromfunction(func, (5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.],
       [ 0.,  4.,  8., 12., 16.]])

In [27]:
np.fromfunction(lambda i, j: i*j, (4, 4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [28]:
np.fromfunction(lambda i, j: i==j, (4, 4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [30]:
t = tuple(x for x in range(10))
t

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

In [31]:
arr = np.fromiter(t, float)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
arr = np.fromiter(t, int)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr = np.fromstring("10,20,30,40,50,60,70,80,90", sep=",", dtype=int)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
arr = np.fromstring("10-20-30-40-50-60-70-80-90", sep="-", dtype=int)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Zeros and Ones

In [37]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros(50, dtype=int)+1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [46]:
for i in np.zeros(1, dtype=int):
    for j in range(10):
        print(i+j)

0
1
2
3
4
5
6
7
8
9


In [47]:
np.ones(100, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [49]:
arr = np.ones(100, dtype=int).reshape(10, 10)

In [50]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [57]:
arr[3:5, 3:5] = (10, 20), (30, 40)

In [58]:
arr

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1, 10, 20,  1,  1,  1,  1,  1],
       [ 1,  1,  1, 30, 40,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [61]:
arr = np.linspace(1, 5, 4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

# Random

In [62]:
arr = np.random.rand(10)

In [63]:
arr

array([0.34075893, 0.13780373, 0.86030594, 0.99935992, 0.70619954,
       0.4746882 , 0.38393984, 0.23258883, 0.43504777, 0.79359651])

In [64]:
arr = np.random.rand(5, 5)
arr

array([[0.05378407, 0.68478983, 0.21780524, 0.70244659, 0.21372106],
       [0.0266868 , 0.86140689, 0.42566306, 0.33285773, 0.42383444],
       [0.2528704 , 0.9731717 , 0.78474811, 0.10245598, 0.40224046],
       [0.43929676, 0.04818586, 0.91726059, 0.08721224, 0.61133063],
       [0.89777382, 0.54528189, 0.98799629, 0.83396599, 0.62154018]])

In [65]:
arr = np.random.randn(10)
arr

array([ 0.28859848,  1.04042325,  0.92702929,  0.69400214,  1.18653157,
       -0.05326253,  1.16184724, -1.1933263 ,  0.37030998,  0.80501228])

In [66]:
arr = np.random.randn(10, 10)
arr

array([[ 0.20323192, -1.67295203,  0.63539494, -0.17509387,  0.15770848,
        -0.84250552,  0.26341517, -0.28391205,  0.69444731, -0.85025178],
       [ 1.03776143, -1.70028121, -0.964619  ,  0.15988883, -0.62560802,
        -1.10400668,  0.3700765 ,  1.4698439 , -1.65172638, -0.70208928],
       [ 0.22688012, -0.642171  , -2.86939352,  1.34144352, -0.83552478,
         0.78155373,  0.07481002,  1.62999009, -0.6738663 ,  1.08628306],
       [ 1.19775835, -0.38167038,  2.22171151,  1.89744681,  0.45412682,
         0.55619441, -0.321257  , -0.11155125,  1.30599631, -1.13901649],
       [ 1.73888006, -0.47244268,  0.54397664,  2.15416915,  0.71570141,
        -1.36971933, -0.56465609, -1.27371766,  1.97121363, -1.17927107],
       [-0.15221553, -1.24010054, -0.31800773,  0.52091393,  0.71302879,
        -0.01654017,  0.00733503, -1.05916196, -0.90271484,  0.73049934],
       [ 1.10670792,  0.14275839, -0.7987126 ,  0.68307195,  0.4955946 ,
        -0.02686275,  0.74643589, -1.43679692

In [78]:
arr = np.random.randint(10)
arr

7

In [79]:
arr = np.random.randint(0, 100, (10, 10))
arr

array([[35, 96,  3,  5, 87, 91, 88, 39, 63, 48],
       [32, 74, 77, 37, 45, 50, 68, 41, 56,  6],
       [66, 86,  1, 64, 45, 68, 73, 37, 44, 38],
       [48,  4, 69,  3, 53, 93, 19, 53, 19, 19],
       [49, 58, 63, 99, 42, 78, 30,  9, 58, 80],
       [34, 93, 29, 34, 75, 48, 12, 35, 83, 27],
       [26, 61, 26, 68, 86, 75, 90, 98, 40, 32],
       [39, 49, 39, 82, 97,  3, 79, 68, 29, 84],
       [13, 97, 10, 76, 37, 71, 88, 73, 68, 42],
       [38, 52, 22, 95, 81, 13, 97, 41, 66,  9]])

# Stastical and math

In [80]:
sin = np.sin(arr)

In [81]:
sin

array([[-0.42818267,  0.98358775,  0.14112001, -0.95892427, -0.82181784,
         0.10598751,  0.0353983 ,  0.96379539,  0.1673557 , -0.76825466],
       [ 0.55142668, -0.98514626,  0.99952016, -0.64353813,  0.85090352,
        -0.26237485, -0.89792768, -0.15862267, -0.521551  , -0.2794155 ],
       [-0.02655115, -0.92345845,  0.84147098,  0.92002604,  0.85090352,
        -0.89792768, -0.67677196, -0.64353813,  0.01770193,  0.29636858],
       [-0.76825466, -0.7568025 , -0.11478481,  0.14112001,  0.39592515,
        -0.94828214,  0.14987721,  0.39592515,  0.14987721,  0.14987721],
       [-0.95375265,  0.99287265,  0.1673557 , -0.99920683, -0.91652155,
         0.51397846, -0.98803162,  0.41211849,  0.99287265, -0.99388865],
       [ 0.52908269, -0.94828214, -0.66363388,  0.52908269, -0.38778164,
        -0.76825466, -0.53657292, -0.42818267,  0.96836446,  0.95637593],
       [ 0.76255845, -0.96611777,  0.76255845, -0.89792768, -0.92345845,
        -0.38778164,  0.89399666, -0.57338187

In [82]:
cos = np.cos(arr)
cos

array([[-0.90369221, -0.18043045, -0.9899925 ,  0.28366219,  0.56975033,
        -0.99436746,  0.99937328,  0.26664293,  0.98589658, -0.64014434],
       [ 0.83422336,  0.17171734, -0.03097503,  0.76541405,  0.52532199,
         0.96496603,  0.44014302, -0.98733928,  0.85322011,  0.96017029],
       [-0.99964746, -0.38369844,  0.54030231,  0.39185723,  0.52532199,
         0.44014302, -0.73619272,  0.76541405,  0.99984331,  0.95507364],
       [-0.64014434, -0.65364362,  0.99339038, -0.9899925 , -0.91828279,
         0.3174287 ,  0.98870462, -0.91828279,  0.98870462,  0.98870462],
       [ 0.30059254,  0.11918014,  0.98589658,  0.03982088, -0.39998531,
        -0.85780309,  0.15425145, -0.91113026,  0.11918014, -0.11038724],
       [-0.84857027,  0.3174287 , -0.74805753, -0.84857027,  0.92175127,
        -0.64014434,  0.84385396, -0.90369221,  0.24954012, -0.29213881],
       [ 0.64691932, -0.25810164,  0.64691932,  0.44014302, -0.38369844,
         0.92175127, -0.44807362, -0.81928825

In [83]:
tan = np.tan(arr)
tan

array([[ 4.73814720e-01, -5.45134011e+00, -1.42546543e-01,
        -3.38051501e+00, -1.44241747e+00, -1.06587872e-01,
         3.54205013e-02,  3.61455441e+00,  1.69749752e-01,
         1.20012724e+00],
       [ 6.61006041e-01, -5.73702254e+00, -3.22685758e+01,
        -8.40771255e-01,  1.61977519e+00, -2.71900612e-01,
        -2.04008160e+00,  1.60656699e-01, -6.11273688e-01,
        -2.91006191e-01],
       [ 2.65605178e-02,  2.40672971e+00,  1.55740772e+00,
         2.34786031e+00,  1.61977519e+00, -2.04008160e+00,
         9.19286404e-01, -8.40771255e-01,  1.77046993e-02,
         3.10309661e-01],
       [ 1.20012724e+00,  1.15782128e+00, -1.15548546e-01,
        -1.42546543e-01, -4.31158197e-01, -2.98738626e+00,
         1.51589471e-01, -4.31158197e-01,  1.51589471e-01,
         1.51589471e-01],
       [-3.17290855e+00,  8.33085685e+00,  1.69749752e-01,
        -2.50925350e+01,  2.29138799e+00, -5.99179998e-01,
        -6.40533120e+00, -4.52315659e-01,  8.33085685e+00,
         9.

In [84]:
np.pi

3.141592653589793

In [85]:
np.degrees(arr)

array([[2005.35228296, 5500.39483326,  171.88733854,  286.47889757,
        4984.73281764, 5213.91593569, 5042.02859715, 2234.53540101,
        3609.63410932, 2750.19741663],
       [1833.46494442, 4239.88768397, 4411.77502251, 2119.94384198,
        2578.31007809, 2864.78897565, 3896.11300689, 2349.12696004,
        3208.56365273,  343.77467708],
       [3781.52144786, 4927.43703813,   57.29577951, 3666.92988884,
        2578.31007809, 3896.11300689, 4182.59190446, 2119.94384198,
        2521.01429858, 2177.2396215 ],
       [2750.19741663,  229.18311805, 3953.4087864 ,  171.88733854,
        3036.67631419, 5328.50749472, 1088.61981075, 3036.67631419,
        1088.61981075, 1088.61981075],
       [2807.49319614, 3323.15521176, 3609.63410932, 5672.2821718 ,
        2406.42273955, 4469.07080202, 1718.87338539,  515.66201562,
        3323.15521176, 4583.66236105],
       [1948.05650344, 5328.50749472, 1661.57760588, 1948.05650344,
        4297.18346348, 2750.19741663,  687.54935416, 2005

In [86]:
np.min(arr)

1

In [87]:
np.max(arr)

99

In [89]:
np.mean(arr)

52.39

In [90]:
np.median(arr)

49.5

In [95]:
np.sort(arr, axis=0)

array([[13,  4,  1,  3, 37,  3, 12,  9, 19,  6],
       [26, 49,  3,  5, 42, 13, 19, 35, 29,  9],
       [32, 52, 10, 34, 45, 48, 30, 37, 40, 19],
       [34, 58, 22, 37, 45, 50, 68, 39, 44, 27],
       [35, 61, 26, 64, 53, 68, 73, 41, 56, 32],
       [38, 74, 29, 68, 75, 71, 79, 41, 58, 38],
       [39, 86, 39, 76, 81, 75, 88, 53, 63, 42],
       [48, 93, 63, 82, 86, 78, 88, 68, 66, 48],
       [49, 96, 69, 95, 87, 91, 90, 73, 68, 80],
       [66, 97, 77, 99, 97, 93, 97, 98, 83, 84]])

In [96]:
np.average(arr)

52.39

In [97]:
np.std(arr)

27.872170708432453

In [99]:
np.percentile(arr, 50, axis=1)

array([55.5, 47.5, 54.5, 33.5, 58. , 34.5, 64.5, 58.5, 69.5, 46.5])

In [100]:
np.var(arr)

776.8579

In [101]:
np.sqrt(np.var(arr))

27.872170708432453